language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.5
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
 - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

