name = "NaiveBayes"
uuid = "b0ceeec0-9a19-467d-a199-44dcc12a78ae"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "^0.23.12"
HDF5 = "^0.12.5"
Interpolations = "^0.12.10"
KernelDensity = "^0.6.0"
StatsBase = "^0.33.1"
